# Generated by Django 3.0.8 on 2020-07-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creator_email',
            field=models.EmailField(default='--------', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='task',
            name='responsible_email',
            field=models.EmailField(default='------', max_length=255, unique=True),
        ),
    ]
